name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential devscripts debhelper dh-python python3-all python3-setuptools python3-flask python3-pip rpm python3-rpm python3-pip-whl
          python3 -m pip install --upgrade pip setuptools wheel build
          sudo apt-get install -y python3 python3-flask python3-pip python3-setuptools
      - name: Set APP_VERSION env
        run: |
          echo "APP_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - name: Build sdist and wheel
        run: |
          python3 -m build
        env:
          APP_VERSION: ${{ env.APP_VERSION }}
      - name: Update debian/changelog version
        run: |
          sed -i "1s/(\$APP_VERSION)/("${APP_VERSION}")/" debian/changelog
        env:
          APP_VERSION: ${{ env.APP_VERSION }}
      - name: Generate debian/changelog
        run: |
          export DEBFULLNAME="GitHub Actions"
          export DEBEMAIL="actions@github"
          dch --create -v "$APP_VERSION" --package co2-sensor "Release $APP_VERSION"
        env:
          APP_VERSION: ${{ env.APP_VERSION }}
      - name: Build deb package
        run: |
          dpkg-buildpackage -us -uc -b
        env:
          APP_VERSION: ${{ env.APP_VERSION }}
      - name: Build rpm package
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-flask python3-pip python3-setuptools
          mkdir -p rpmbuild/SOURCES
          tar czf rpmbuild/SOURCES/co2-sensor-${{ env.APP_VERSION }}.tar.gz --transform "s,^,co2-sensor-${{ env.APP_VERSION }}/," .
          rpmbuild --define "_topdir $(pwd)/rpmbuild" --define "version ${{ env.APP_VERSION }}" --nodeps -ba co2-sensor.spec
        env:
          APP_VERSION: ${{ env.APP_VERSION }}
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
            ../co2-sensor_*.deb
            rpmbuild/RPMS/noarch/co2-sensor-*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
